export enum TRAITS {
    SHARPSHOOTER = "sharpshooter",
    TOUGH = "tough",
    FAST_LEARNER = "fast_learner",
    HANDY = "handy",
    GREEN_THUMB = "green_thumb",
    HEALER = "healer",
    CHARISMATIC = "charismatic",
    ANIMAL_WHISPERER = "animal_whisperer",
    MINER = "miner",
    SCIENTIST = "scientist",
    ATHLETE = "athlete",
    ARTISAN = "artisan",
    SNEAKY = "sneaky",
    LUCKY = "lucky",
    TECH_SAVVY = "tech_savvy",
    DIPLOMAT = "diplomat",
    MUSICIAN = "musician",
    NURTURER = "nurturer",
    MYSTERIOUS = "mysterious",
    JOKER = "joker",
}